import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import Header from './_components/Header/Header';
import Sidebar from './_components/Sidebar/Sidebar';
import Footer from './_components/Footer/Footer';

const notoSans = Noto_Sans({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: { template: '%s / TopApp', default: 'Welcome / TopApp' },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`${notoSans.className}`}>
                <Header />
                <div>
                    <Sidebar />
                    <div>{children}</div>
                </div>
                <Footer />
            </body>
        </html>
    );
}
